version: '3'
services:
# Incase need local mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  product-service-migrate:
    build:
      context: ./product-service
      dockerfile: Dockerfile.migrate
    depends_on:
      - postgres
    command: ["/migrate"]

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  transaction-service-migrate:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile.migrate
    depends_on:
      - clickhouse
    command: ["/migrate"]

  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - clickhouse
      - minio

  transaction-service-cron:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile.cron
    depends_on:
      - clickhouse
      - minio

  # orchestrator-service:
  #   build:
  #     context: ./orchestrator-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8084:8084"

# Incase need local postgres
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9001:9000"
    volumes:
      - ./minio-data:/data

  minio-migrate:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minio minio123;\
      /usr/bin/mc mb myminio/transaction;
      /usr/bin/mc policy download myminio/transaction;
      exit 0;
      "

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - product-service
      - transaction-service
      - transaction-service-cron

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
     - "2181:2181"
    networks:
    - default

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
     - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - default


networks:
  default:
    driver: bridge