FROM golang:1.21
WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . .
COPY .env.docker ../../.env
RUN go build -o /transaction-service-cron ./cmd/cron/main.go
EXPOSE 8083
CMD ["/transaction-service-cron"]